# Generated by Django 4.1 on 2022-08-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Цифра')),
                ('symbol', models.CharField(max_length=1, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'Справочник классов',
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_group', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания группы учеников')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('course', models.IntegerField(blank=True, choices=[(1, 1), (2, 2)], default=1, null=True)),
            ],
            options={
                'verbose_name': 'Група учеников',
                'verbose_name_plural': 'Группы учеников',
            },
        ),
        migrations.CreateModel(
            name='RatingItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Статус оценки')),
            ],
            options={
                'verbose_name': 'статус оценки',
                'verbose_name_plural': 'Справочник статусов оценок',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Оценка')),
                ('created', models.DateField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.groupstudent', verbose_name='Наименование класса')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
