# Generated by Django 4.1 on 2022-08-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.ratingitemstatus', verbose_name='Статус оценки'),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='journal.grade', verbose_name='Наименование класса'),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='subjects',
            field=models.ManyToManyField(to='lessons.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='lessons',
            field=models.ManyToManyField(related_name='grade', to='lessons.lesson', verbose_name='Уроки класса'),
        ),
    ]
