# Generated by Django 4.1 on 2022-08-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_score_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='symbol',
        ),
    ]
