# Generated by Django 4.1 on 2022-08-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_score_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupstudent',
            old_name='grade',
            new_name='group_id',
        ),
    ]
