# Generated by Django 4.1 on 2022-08-15 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_rename_grade_groupstudent_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupstudent',
            old_name='group_id',
            new_name='grade',
        ),
    ]
