# Generated by Django 4.1 on 2022-08-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_topic_subject_lesson_subject'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(related_name='teachers', to='lessons.subject', verbose_name='Ведет предметы'),
        ),
    ]
