# Generated by Django 4.1 on 2022-08-15 01:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_alter_teacher_lessons'),
        ('lessons', '0004_remove_topic_subject_lesson_subject'),
        ('journal', '0006_alter_score_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistantLearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('main_text', models.TextField(max_length=3000)),
                ('link', models.URLField(blank=True, null=True)),
                ('additional_text', models.TextField(blank=True, max_length=3000, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.teacher')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.groupstudent')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='lesson_files_upload', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pptx', 'xls', 'csv'])])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('distant_learning_lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='distant_learning.distantlearninglesson')),
            ],
        ),
    ]
