# Generated by Django 4.1 on 2022-08-29 19:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='lesson_files_upload', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pptx', 'xls', 'csv'])])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DistantLearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('course', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('main_text', models.TextField(max_length=3000)),
                ('link', models.URLField(blank=True, null=True)),
                ('additional_text', models.TextField(blank=True, max_length=3000, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
