# Generated by Django 4.1 on 2022-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distant_learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distantlearninglesson',
            name='group',
        ),
        migrations.AddField(
            model_name='distantlearninglesson',
            name='course',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
    ]
