# Generated by Django 4.1 on 2022-08-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distant_learning', '0001_initial'),
        ('people', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distantlearninglesson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.teacher'),
        ),
        migrations.AddField(
            model_name='distantlearninglesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.subject'),
        ),
        migrations.AddField(
            model_name='additionalfiles',
            name='distant_learning_lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='distant_learning.distantlearninglesson'),
        ),
    ]
