# Generated by Django 4.1 on 2022-08-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_topic_subject_lesson_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfiles',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonimages',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonvideos',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lessons.lesson'),
        ),
    ]
