# Generated by Django 4.1 on 2022-08-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_additionalfiles_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalfiles',
            old_name='video',
            new_name='add_file',
        ),
    ]
